import sys

import requests
import os
from dotenv import load_dotenv
from sandbox_mbpp.config import SandboxConfig
from sandbox_mbpp.sandbox import Sandbox


def call_openrouter(prompt, model='openrouter/free'):
    """Make a call to OpenRouter API"""
    # Usage
    # response = call_openrouter("4 + 2 =")
    # print(response)
    load_dotenv()
    OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
    headers = {
        'Authorization': f'Bearer {OPENROUTER_API_KEY}',
        'Content-Type': 'application/json'
    }

    payload = {
        'model': model,
        'messages': [
            {'role': 'user', 'content': prompt}
        ]
    }

    try:
        response = requests.post(
            'https://openrouter.ai/api/v1/chat/completions',
            json=payload,
            headers=headers,
            timeout=30
        )
        response.raise_for_status()  # Raises exception for bad status codes

        result = response.json()
        return result['choices'][0]['message']['content']

    except requests.exceptions.Timeout:
        return "Error: Request timed out"
    except requests.exceptions.HTTPError as e:
        return f"HTTP Error: {e}"
    except requests.exceptions.RequestException as e:
        return f"Request failed: {e}"
    except KeyError:
        return "Error: Unexpected API response format"


task = {
    "text": "Write a function to find the n-th rectangular number.",
    "code": "def find_rect_num(n):\r\n  return n*(n + 1) ",
    "task_id": 35,
    "test_setup_code": "",
    "test_list": ["assert find_rect_num(4) == 20", "assert find_rect_num(5) \
== 30", "assert find_rect_num(6) == 42"],
    "challenge_test_list": []
    }


def solve_task(task: dict):
    task_def = task["text"]
    test_list = task["test_list"]
    prompt = task_def + "\nTest list: " + str(test_list)
    prompt += " reply with nothing but the code starting by ```python"
    print("Sending request to openrouter...")
    response = call_openrouter(prompt)
    print("Openrouter response received")
    if response.startswith("```python"):
        response = response[10:-4]
    else:
        print(f"response doesn't start with '```python':\n {response}")
        sys.exit(1)
    print(f"Code generated by openrouter:\n{response}")
    code = response + '\n\n'
    for test in test_list:
        func_call = test[6:].split('==')[0]
        test_code = f"""\n\ntry:\n    {test}\n    print("Passed test: \
'{test}'")\nexcept AssertionError:\n    print(f"Failed test: '{test}' got \
{{{func_call}}} instead")"""
        code += '\n\n' + test_code
    config = SandboxConfig()
    server_path = 'src/fastmcp_server.py'
    sandbox = Sandbox(config, server_path)
    sandbox.configure()
    result = sandbox.execute(code)
    if result.success:
        print(result.output)
        split_output = result.output.split('\n')
        passed = True
        for line in split_output:
            if len(line) > 0 and not line.startswith('Passed test: '):
                passed = False
                break
        if passed:
            print("All tests have passed successfully!")
        else:
            print("Some tests have failed. More work to be done")
    else:
        print(result.error)


solve_task(task)
